version: '2'
services:
  cubbroker:
    container_name: cubbroker
    image: cubrid/cubrid:11.2
    depends_on:
      - cubserver
    environment:
      - CUBRID_COMPONENTS=BROKER
      - CUBRID_DB_HOST=cubserver
      - CUBRID_DB=newamisdb
      - CUBRID_CHARSET=ko_KR.utf8
      - CUBRID_LOCALE=ko_KR
    ports:
      - "30000:33000"
    links:
      - cubserver
  cubserver:
    container_name: cubserver
    image: cubrid/cubrid:11.2
    environment:
      - CUBRID_COMPONENTS=SERVER
      - CUBRID_DB=newamisdb
      - CUBRID_CHARSET=ko_KR.utf8
      - CUBRID_LOCALE=ko_KR
    volumes:
      - cubriddata:/var/lib/cubrid
volumes:
  cubriddata: {}
